name: Setup
description: "Initial setup AWS auth and docker credentials"
inputs:
  iam_role:
    description: 'AWS IAM role to assume'
    required: true
    type: string
  region:
    description: "AWS region"
    required: false
    type: string
    default: 'eu-west-2'
  self_hosted:
    description: "Flag if the build is using a self-hosted runner"
    type: boolean
    required: false
runs:
  using: 'composite'
  steps:
  - name: Check out code
    uses: actions/checkout@v2

  - name: Set up Docker Buildx selfhosted
    uses: docker/setup-buildx-action@v2
    if: ${{ inputs.self_hosted == true }}
    with:
      driver: kubernetes

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2
    if: ${{ inputs.self_hosted == false}}

  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      role-to-assume: ${{ inputs.iam_role }}
      aws-region: ${{ inputs.region }}

  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1