name: Setup
description: "Initial setup GCP auth and docker credentials"
inputs:
  service_account:
    description: 'GCP Service account to use with Workload identity federation'
    required: true
    type: string
  project_id:
    description: "GCP project ID"
    type: string
    required: true
  workload_identity_provider:
    description: "GCP Workload identity provider for Github actions"
    required: true
    type: string
  self_hosted:
    description: "Flag if the build is using a self-hosted runner"
    type: boolean
    required: false
runs:
  using: 'composite'
  steps:
  - name: Check out code
    uses: actions/checkout@v3

  - name: Set up Docker Buildx selfhosted
    uses: docker/setup-buildx-action@v2
    if: ${{ inputs.self_hosted == true }}
    with:
      driver: kubernetes

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2
    if: ${{ inputs.self_hosted == false}}

  - name: GCP authenticate
    uses: 'google-github-actions/auth@v0.4.1'
    with:
      workload_identity_provider: ${{ inputs.workload_identity_provider }}
      service_account: ${{ inputs.service_account }}
  - name: Setup GCLOUD
    uses: google-github-actions/setup-gcloud@v0.6.0
    with:
      project_id: ${{ inputs.project_id }}

  # Configure Docker to use the gcloud command-line tool as a credential
  # helper for authentication
  - name: Configure docker
    shell: bash
    run: |-
      gcloud --quiet auth configure-docker
