name: Build and push a docker image

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      app_name:
        description: 'Application name to be used for building the image'
        required: true
        type: string
      registry:
        description: "Docker registry to push the image"
        required: false
        default: eu.gcr.io/dextcloud-2038082
        type: string

jobs:
  build_and_push:
    name: Build and push a docker image
    runs-on: ubuntu-latest 

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      run: |
        docker build -t $INPUT_REGISTRY/$INPUT_APP_NAME:$GITHUB_SHA .
        