name: Build and push to Dockerhub

on:
  workflow_call:
    inputs:
      app_name:
        description: 'Application name to be used for building the image'
        required: true
        type: string
      dockerhub_registry:
        description: "DockerHub registry to push the image"
        required: false
        default: docker.io/dextcloudonprem
        type: string

    secrets:
      dockerhub_username:
        required: true
      dockerhub_password:
        required: true

jobs:
  build:
    name: Build and push a docker image
    runs-on: [self-hosted]
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx selfhosted
      uses: docker/setup-buildx-action@v2
      if: ${{ inputs.self_hosted == true }}
      with:
        driver: kubernetes

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.6.0
      with:
        java-version: 11
        maven-version: 3.6.3

    - name: Build app, build and push image
      run: |
        mvn -DskipTests clean install
        grep -Eo "<version>[0-9]+.[0-9]+.[0-9]+" pom.xml | grep -Eo "[0-9]+\\.[0-9]+\\.[0-9]+" | head -n 1 > next_version
        docker build -t ${{ inputs.dockerhub_registry }}/${{ inputs.app_name}}:${{ github.ref_name }} --build-arg JAR_FILE=target/${{ inputs.java_target_name}}-`cat next_version`.jar .
        docker login -u "${{ secrets.dockerhub_username }}" -p "${{ secrets.dockerhub_password }}"
        docker push ${{ inputs.dockerhub_registry }}/${{ inputs.app_name}}:${{ github.ref_name }}
