name: Build and push a docker image

on:
  workflow_call:
    inputs:
      app_name:
        description: 'Application name to be used for building the image'
        required: true
        type: string
      registry:
        description: "Docker registry to push the image"
        required: false
        default: eu.gcr.io/dextcloud-2038082
        type: string
      service_account:
        description: 'GCP Service account to use with Workload identity federation'
        required: true
        type: string
      workload_identity_provider:
        description: "GCP Workload identity provider for Github actions"
        required: true
        type: string
jobs:
  permissions:
    id-token: write
    contents: write

  build_and_push:
    name: Build and push a docker image
    runs-on: ubuntu-latest 

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      run: |
        docker build -t ${{ inputs.registry }}/${{ inputs.app_name}}:$GITHUB_SHA .

    - name: GCP authenticate
      uses: 'google-github-actions/auth@v0.4.1'
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - name: Configure docker
      run: |-
        gcloud --quiet auth configure-docker

    - name: Push image
      run: docker push ${{ inputs.registry }}/${{ inputs.app_name}}:$GITHUB_SHA
