name: Build and push a docker image

on: [push, pull_request, workflow_call]

jobs:
  build_and_push:
    name: Build and push a docker image
    runs-on: ubuntu-latest 

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      run: |
        registry=eu.gcr.io/dextcloud-203808
        if [ $INPUT_REGISTRY]; then
          registry=$INPUT_REGISTRY;
        fi
        docker build -t $registry/$INPUT_APP_NAME:$GITHUB_SHA .
        