name: Initial setup of GCP auth and docker credentials
on:
  workflow_call:
    inputs:
      service_account:
        description: 'GCP Service account to use with Workload identity federation'
        required: true
        type: string
      project_id:
        description: "GCP project ID"
        type: string
      workload_identity_provider:
        description: "GCP Workload identity provider for Github actions"
        required: true
        type: string

jobs:
  docker_gcr_setup:
    name: Setup GCR and Docker access
    runs-on: ubuntu-latest 
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: GCP authenticate
      uses: 'google-github-actions/auth@v0.4.1'
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
    - name: Setup GCLOUD
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ inputs.project_id }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - name: Configure docker
      run: |-
        gcloud --quiet auth configure-docker
