name: Bump and commit new java app version

on:
  workflow_call:

jobs:
  bump_version:
    name: Bump java app version
    runs-on: ubuntu-latest 
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Bump version
      run: |
        mvn validate -DbumpPatch
        git add pom.xml
        git config --global user.name 'Github Actions Dextcloud Automation'
        git config --global user.email 'github-actions-dextcloud@users.noreply.github.com'
        git commit -m "[skip ci] Bump pom.xml version"
        git push
