name: Java App build and run tests

on: 
  workflow_call:
    inputs:
      config_from_vault:
        type: boolean
        required: false
        description: "Fetch config from Vault and expose it as SPRING_APPLICATION_JSON variable"
      auth_server:
        type: string
        required: false
        default: http://java-auth.dext-core:9070
        description: "HTTP URL for dext authentication service"
    secrets:
      vault_url:
        required: false
      vault_token:
        required: false
      slack_webhook:
        required: false

jobs:
  build_and_test:
    name: Test Java app
    runs-on: [self-hosted]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'

    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.4.0
      with:
        java-version: 11
        maven-version: 3.6.3

    - name: Export spring profile
      if: ${{ inputs.config_from_vault }} == true
      id: spring_profile
      run: |
        echo "::echo::on"
        echo 'SPRING_APPLICATION_JSON<<EOF' >> $GITHUB_ENV
        curl --max-time 10  --connect-timeout 10 -Ss -H "X-Vault-Token: ${{ secrets.vault_token }}" -X GET ${{ secrets.vault_url }} | jq .data >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Run the tests
      env:
        VAULT_TOKEN: ${{ secrets.vault_token }}
        APP_AUTH_SERVER_URL: ${{ inputs.auth_server }}
        TESTCONTAINERS_RYUK_DISABLED: "true"
      run: |
        echo "${SPRING_APPLICATION_JSON}"
        mvn -B clean test

    - name: Send slack update failure
      uses: DMSDigital/github-workflows/.github/actions/send-slack-message@master
      if: ${{ failure() }}
      with:
        slack_webhook: ${{ secrets.slack_webhook }}
        text: "Tests for ${{ inputs.app_name }} have failed. URL: ${{ github.repositoryUrl }}/runs/${{ github.github.run_id	}}\""