name: Java App build and run tests

on: 
  workflow_call:
    inputs:
      config_from_vault:
        type: boolean
        required: false
        description: "Fetch config from Vault and expose it as SPRING_APPLICATION_JSON variable"
    secrets:
      vault_url:
        required: false
      vault_token:
        required: false

jobs:
  build_and_test:
    name: Test Java app
    runs-on: ubuntu-latest 

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Export spring profile
      if: ${{ inputs.config_from_vault }} == true
      run: |
        export SPRING_APPLICATION_JSON=$(curl --max-time 10  --connect-timeout 10 -Ss -H "X-Vault-Token: {{ secrets.vault_token }}" -X GET "${secrets.vault_url}" | jq .data)
        echo "::set-env name=SPRING_APPLICATION_JSON::$SPRING_APPLICATION_JSON"
    - name: Run the tests
      run: |
        mvn test
        