name: Java App build and run tests

on: [workflow_call]

jobs:
  build_and_test:
    name: Test Java app
    runs-on: ubuntu-latest 

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Run the tests
      run: mvn test
        