name: Node App build and run tests

on:
  workflow_call:
    secrets:
      slack_webhook:
        required: false


jobs:
  build_and_test:
    name: Build and test NodeJS app
    runs-on: ubuntu-latest 

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 17.8
        cache: 'yarn'

    - name: Install dependencies and run tests
      run: |
        yarn install
        yarn run test

    - name: Send slack update failure
      uses: DMSDigital/github-workflows/.github/actions/send-slack-message@master
      if: ${{ failure() }}
      with:
        slack_webhook: ${{ secrets.slack_webhook }}
        text: "Docker build for ${{ inputs.app_name }} has failed. URL: ${{ github.repositoryUrl }}/runs/${{ github.github.run_id	}}\""