name: Node App build and run tests

on: [push, pull_requests]

jobs:
  build_and_test:
    name: Build and test NodeJS app
    runs-on: ubuntu-latest 

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 17.8
        cache: 'yarn'

    - name: Install dependencies and run tests
      run: |
        yarn install
        yarn run test
        